version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Hotel_web:/var/www/html
    depends_on:
      - db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    privileged: true 

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
      MYSQL_USER: hotel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --secure-file-priv=""
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - ./grant-file-priv.sql:/docker-entrypoint-initdb.d/01-grant-file-priv.sql

volumes:
  db_data:
